document.addEventListener('DOMContentLoaded', () => {
    updateDate();
    fetchNews();

    // Auto-refresh frontend news every 30 minutes (to match backend)
    setInterval(fetchNews, 1800000); // 30 mins

    // Auto-update the date header every minute (so it flips at midnight)
    setInterval(updateDate, 60000);
});

function updateDate() {
    const now = new Date();

    // Marathi Days and Months (Optional, user asked for Marathi but strict date format usually fine)
    // We will use Intl.DateTimeFormat for proper localization
    const dateOptions = { year: 'numeric', month: 'long', day: 'numeric' };
    const dayOptions = { weekday: 'long' };

    const dateStr = now.toLocaleDateString('mr-IN', dateOptions);
    const dayStr = now.toLocaleDateString('mr-IN', dayOptions);

    document.getElementById('current-date').textContent = dateStr;
    document.getElementById('current-day').textContent = dayStr;
    document.getElementById('year').textContent = now.getFullYear();
}

async function fetchNews() {
    const container = document.getElementById('news-container');

    try {
        // Update "Last Checked" display
        const now = new Date();
        const timeStr = now.toLocaleTimeString('mr-IN', { hour: '2-digit', minute: '2-digit' });
        const lastUpdateElem = document.getElementById('last-updated');
        if (lastUpdateElem) {
            lastUpdateElem.textContent = timeStr;
        }

        // We expect news_data.json to be generated by the python script
        const response = await fetch('news_data.json');
        if (!response.ok) {
            throw new Error('News data not found. Please ensure backend script is running.');
        }

        const newsData = await response.json();

        if (newsData.length === 0) {
            container.innerHTML = '<div class="loading-spinner">No news updates available at the moment.</div>';
            return;
        }

        renderNews(newsData);
    } catch (error) {
        console.error('Error loading news:', error);
        container.innerHTML = `
            <div class="loading-spinner" style="color:red">
                <i class="fas fa-exclamation-triangle"></i> 
                Unable to load news. Ensure fetch_news.py is running.
            </div>`;
    }
}

function renderNews(newsItems) {
    const container = document.getElementById('news-container');
    container.innerHTML = ''; // Clear loading spinner

    newsItems.forEach(item => {
        const card = document.createElement('div');
        card.className = 'news-card';

        // Format timestamp relative (e.g., "2 hours ago") or just time
        const dateObj = new Date(item.date);
        const timeStr = dateObj.toLocaleTimeString('mr-IN', { hour: '2-digit', minute: '2-digit' });

        card.innerHTML = `
            <img src="${item.image}" alt="News Image" class="card-image" onerror="this.src='https://via.placeholder.com/300x200?text=Latur+News'">
            <div class="card-content">
                <span class="source-badge">${item.source}</span>
                <h3 class="news-title">${item.title}</h3>
                <p class="news-desc">${item.description}</p>
                <div class="card-footer">
                    <span><i class="far fa-clock"></i> ${timeStr}</span>
                    <a href="${item.link}" target="_blank" class="read-more">
                        More <i class="fas fa-arrow-right"></i>
                    </a>
                </div>
            </div>
        `;
        container.appendChild(card);
    });
}
